spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5432/dmoney
    username: postgres
    password: root
  liquibase:
    enabled: true
    changelog: classpath:db/changelog/db.changelog-master.xml
    contexts: dev
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: ${JWT_SECRET}